---
- name: Ansible Playbook to Install and Setup Apache on Ubuntu
  hosts: webserver
  become: true
  become_method: ansible.legacy.sr
  gather_facts: false
  tasks:
    [...]
    - name: Open port 80
      become_flags: "-r rar_e4cea3cea6e87ab64741a2282121b087c777f877075c0455e830f7c0 -t 5"
      ansible.builtin.import_role:
        name: mallory_net_input
      vars:
        mallory_net_input_protocol: tcp
        mallory_net_input_port: 80
        mallory_net_input_state: accepting
  