---
- name: Create ssh key
  import_playbook: playbooks/create-sshkey.yml

- name: Start docker
  import_playbook: playbooks/start-docker.yml

- name: Playbook
  become_method: ansible.legacy.capable
  ansible.builtin.import_playbook: scenario_paper.yml

- name: Test Apache2
  connection: local
  hosts: localhost
  become: false
  tasks:
    - name: Test Apache2
      ansible.builtin.uri:
        url: "http://{{ ansible_host }}/index.html"
        status_code: 200
  ignore_errors: true
