all:
  vars:
    ansible_ssh_private_key_file: "{{ inventory_dir }}/ansible_rsa"
    ansible_remote_tmp: /tmp
    ansible_network: 172.21.0.0
    ansible_netmask: 16
    ansible_gateway: 172.21.0.1
  hosts:
    localhost:
      ansible_connection: local
      ansible_user: lechatp
      keep_docker: false
      ssh_key_path: "{{ inventory_dir }}/ansible_rsa"
      dockerfile: "Dockerfile"
      webserver_ip: 172.21.0.2
    docker:
      ansible_host: 172.21.0.2
      ansible_user: lechatp
      ansible_become_pass: "lechatp"
    webserver:
      ansible_host: 172.21.0.2 
      ansible_user: lechatp
      ansible_become_pass: "lechatp"
      http_host: RootAsWeb
      http_conf: rootasweb.conf
      http_port: 80
      http_log_dir: /var/log/apache2