all:
  hosts:
    localhost:
      ansible_user: lechatp
      ansible_host: 172.21.0.2
      ansible_network: 172.21.0.0
      ansible_netmask: 16
      ansible_gateway: 172.21.0.1
      ssh_key_path: "{{ playbook_dir }}/../inventory/ansible_rsa"
      keep_docker: false
      dockerfile: "Dockerfile"
    docker:
      ansible_user: lechatp
      ansible_become_pass: "lechatp"
      ansible_host: 172.21.0.2
      ansible_network: 172.21.0.0
      ansible_netmask: 16
      ansible_gateway: 172.21.0.1
      ansible_ssh_private_key_file: "{{ playbook_dir }}/inventory/ansible_rsa"
      http_host: RootAsWeb
      http_conf: rootasweb.conf
      http_port: 80
    webserver:
      ansible_user: lechatp
      ansible_become_pass: "lechatp"
      ansible_host: 172.21.0.2
      ansible_network: 172.21.0.0
      ansible_netmask: 16
      ansible_gateway: 172.21.0.1
      ansible_ssh_private_key_file: "{{ playbook_dir }}/inventory/ansible_rsa"
      http_host: RootAsWeb
      http_conf: rootasweb.conf
      http_port: 80