---
- name: Copy HTML template file
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/var/www/{{ http_host }}/index.html"
  vars:
    item: '{{ lookup("first_found", dict(files=["../templates/index-template.html.j2"], skip=True)) }}'