---
- name: Install Rust
  ansible.builtin.import_tasks: install_rust.yml
- name: Check if RootAsRole is installed
  ansible.builtin.command:
    cmd: command -v sr
  register: sr
  failed_when: false
  changed_when: false

- name: Clone RootAsRole repository
  when: sr.rc != 0
  ansible.builtin.git:
    repo: 'https://github.com/LeChatP/RootAsRole.git'
    dest: '/tmp/RootAsRole'
    clone: true
    update: true
    version: "{{ rootasrole_branch }}"
  become: false
  register: git

- name: Performing install xtask
  when: sr.rc != 0
  ansible.builtin.command:
    cmd: 'cargo xtask install -bip sudo'
    chdir: '/tmp/RootAsRole'
  become: false
  timeout: 600
  args:
    creates:
      - '/usr/bin/sr'
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.cargo/bin"

- name: Cat /etc/security/rootasrole.json
  ansible.builtin.command:
    cmd: 'cat /etc/security/rootasrole.json'
  register: rootasrole
  become: true
  become_method: ansible.builtin.sudo
  changed_when: false

- name: Set no-password if variable is set
  ansible.builtin.template:
    src: "{{ playbook_dir }}/templates/pam_sr"
    dest: "/etc/pam.d/sr"
    mode: "0644"
    owner: root
    group: root
  when: "rootasrole_sr_password == 'no'"
  become: true
  become_method: ansible.builtin.sudo
