---
- name: Check if gensr is installed
  ansible.builtin.command:
    cmd: gensr --version
  register: gensr_version
  failed_when: false
  changed_when: false
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.cargo/bin"

- name: Clone gensr repository
  when: gensr_version.rc != 0
  ansible.builtin.git:
    repo: 'https://github.com/LeChatP/RootAsRole-utils.git'
    dest: '/tmp/RootAsRole-utils'
    clone: true
    update: true
    version: "{{ rootasrole_branch }}"

- name: Performing install
  when: gensr_version.rc != 0
  ansible.builtin.command:
    cmd: 'cargo install --path .'
    chdir: '/tmp/RootAsRole-utils'
  timeout: 600
  args:
    creates:
      - '{{ ansible_env.HOME }}/.cargo/bin/release/gensr'
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.cargo/bin"

- name: Copy gensr to /usr/bin
  when: gensr_version.rc != 0
  ansible.builtin.command:
    cmd: cp {{ ansible_env.HOME }}/.cargo/bin/gensr /usr/bin/gensr
  args:
    creates:
      - '/usr/bin/gensr'
  become: true
