---
- name: Clone RootAsRole repository
  ansible.builtin.git:
    repo: 'https://github.com/LeChatP/RootAsRole.git'
    dest: '/tmp/RootAsRole'
    clone: true
    update: true
    version: 'develop'
  become: false
  register: git
  changed_when: false
  notify: Install RootAsRole

- name: Cat /etc/security/rootasrole.json
  ansible.builtin.command:
    cmd: 'cat /etc/security/rootasrole.json'
  register: rootasrole
  become: true
  become_method: ansible.builtin.sudo
  changed_when: false

- name: Set no-password if variable is set
  ansible.builtin.template:
    src: "{{ playbook_dir }}/templates/pam_sr"
    dest: "/etc/pam.d/sr"
    mode: "0644"
    owner: root
    group: root
  when: "sr_password == 'no'"
  become: true
  become_method: ansible.builtin.sudo
  changed_when: false
