---
- name: Clone RootAsRole repository
  git:
    repo: 'https://github.com/LeChatP/RootAsRole.git'
    dest: '/tmp/RootAsRole'
    clone: true
    update: true
    version: 'develop'
  become: false
  register: git

- name: Install Dependencies script
  ansible.builtin.shell:
    cmd: './dependencies.sh -yd'
    chdir: '/tmp/RootAsRole'
  register: deps
  timeout: 600
  become: true
  when: git.changed

- name: Run configuration script
  ansible.builtin.shell:
    cmd: 'yes | ./configure.sh -yd'
    chdir: '/tmp/RootAsRole'
  become: true
  become_method: sudo
  ignore_errors: true
  register: configure
  timeout: 300
  when: deps.changed

- name: exit if configure failed
  fail:
    msg: "Configure failed"
  when: configure.rc != 0
  become: false

- name: Install RootAsRole
  ansible.builtin.shell:
    cmd: 'make install'
    chdir: '/tmp/RootAsRole'
  become: false
  timeout: 600
  when: git.changed

- name: cat /etc/security/rootasrole.json
  ansible.builtin.shell:
    cmd: 'cat /etc/security/rootasrole.json'
  register: rootasrole
  become: true
  become_method: sudo
  changed_when: false

- name: Set no-password if variable is set
  ansible.builtin.template:
    src: "../templates/pam_sr"
    dest: "/etc/pam.d/sr"
  when: "sr_password == 'no'"
  become: true
  become_method: sudo
  changed_when: false