---

- name: Read config file
  ansible.builtin.include_vars:
    file: /etc/security/rootasrole.json
    name: rootasrole_config
- name: Convert config to json
  ansible.builtin.set_fact:
    rootasrole_config: "{{ rootasrole_config | to_nice_json }}"
# Task to list all roles
- name: List all roles
  ansible.builtin.debug:
    var: rootasrole_config
