---
- name: Create new role
  ansible.builtin.command: 'chsr newrole {{ rootasrole_role_name }}'
  register: newrole
  changed_when: newrole.rc == 0
  failed_when: newrole.rc != 0
  ignore_errors: true
  tags: ['newrole']
