FROM ubuntu:latest

RUN apt update

# install ssh
RUN apt-get update \
    && apt-get install -y \
        openssh-server iputils-ping telnet iproute2 sudo \
        git clang curl build-essential libelf-dev llvm \
        linux-tools-generic binutils-dev libcap-dev libclang-dev \
        libdbus-1-dev pkg-config

RUN apt-get install -y \
    libacl1-dev

# Expose SSH port
EXPOSE 22

# create user
RUN adduser --home /home/{{ ansible_user }} {{ ansible_user }}
RUN echo "{{ ansible_user }}:{{ ansible_user }}" | chpasswd

# create ansible group
RUN groupadd ansible
RUN usermod -aG ansible {{ ansible_user }}

# create ssh directory
RUN mkdir /home/{{ ansible_user }}/.ssh
RUN mkdir -pm0755 /run/sshd

# copy ssh public key
COPY ansible_rsa.pub /home/{{ ansible_user }}/.ssh/authorized_keys

# set permissions
RUN chown -R {{ ansible_user }}:{{ ansible_user }} /home/{{ ansible_user }}/.ssh
RUN chmod 700 /home/{{ ansible_user }}/.ssh
RUN chmod 600 /home/{{ ansible_user }}/.ssh/authorized_keys

# allow ssh user to sudo
RUN echo "%ansible ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

USER {{ ansible_user }}

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

RUN . "$HOME/.cargo/env"

USER root

# start ssh service
CMD ["/usr/sbin/sshd", "-D"]