FROM ubuntu:latest

RUN apt update

# install ssh
RUN apt-get update \
    && apt-get install -y openssh-server iputils-ping telnet iproute2 sudo git

# Expose SSH port
EXPOSE 22

# create user
RUN adduser --home /home/{{ ansible_user }} {{ ansible_user }}
RUN echo "{{ ansible_user }}:{{ ansible_user }}" | chpasswd

# create ansible group
RUN groupadd ansible
RUN usermod -aG ansible {{ ansible_user }}

# create ssh directory
RUN mkdir /home/{{ ansible_user }}/.ssh
RUN mkdir -pm0755 /run/sshd

# copy ssh public key
COPY ansible_rsa.pub /home/{{ ansible_user }}/.ssh/authorized_keys

# set permissions
RUN chown -R {{ ansible_user }}:{{ ansible_user }} /home/{{ ansible_user }}/.ssh
RUN chmod 700 /home/{{ ansible_user }}/.ssh
RUN chmod 600 /home/{{ ansible_user }}/.ssh/authorized_keys

# allow ssh user to sudo
RUN echo "%ansible ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers


# expose http port
EXPOSE 80

# start ssh service
CMD ["/usr/sbin/sshd", "-D"]