---
- name: Configure Docker
  hosts: localhost
  connection: local
  become: true
  become_method: ansible.builtin.sudo
  tasks:
    - name: Docker Network
      community.docker.docker_network:
        name: RootAsAnsibleNetwork
        state: present
        ipam_config:
          - subnet: "{{ ansible_network }}/{{ ansible_netmask }}"
            gateway: "{{ ansible_gateway }}"
    - name: Create image
      ansible.builtin.template:
        src: "{{ item }}"
        dest: ../inventory/Dockerfile
        owner: "root"
        group: "root"
        mode: '0644'
      vars:
        item: '{{ lookup("first_found", dict(files=["../templates/Dockerfile.j2"], skip=True)) }}'
    - name: Build image
      community.docker.docker_image:
        name: rootasansible
        build:
          path: ../inventory
        source: build
        force_source: true
        state: present
    - name: Start container
      community.docker.docker_container:
        name: rootasansiblecontainer
        image: rootasansible
        state: started
        capabilities:
          - NET_ADMIN
        expose:
          - "22"
        networks:
          - name: RootAsAnsibleNetwork
            ipv4_address: "{{ ansible_host }}"
